apiVersion: v1
kind: Secret
metadata:
  name: rds-credentials
  namespace: smart-farm
type: Opaque
data:
  # هذا هو الـ Base64 لرابط الداتابيز. 
  # مثال: echo -n "postgresql://farmnetadmin:SuperSecretPassword123!@<RDS_ENDPOINT>:5432/farmnetdb" | base64
  DATABASE_URL: cG9zdGdyZXNxbDovL2Zhcm1uZXRhZG1pbjpTdXBlclNlY3JldFBhc3N3b3JkMTIzIUBMT0NBTEhPU1Q6NTQzMi9mYXJtbmV0ZGI=